# Generated by Django 4.1.7 on 2023-03-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=50)),
                ('emp_salary', models.CharField(max_length=10)),
                ('emp_present', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GarbageTrucks',
            fields=[
                ('truck_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('number_plate', models.CharField(max_length=15)),
                ('max_capacity', models.CharField(max_length=10)),
                ('truck_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pickup',
            fields=[
                ('pickup_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=1000)),
            ],
        ),
    ]
